services:
  # Définition du service "bank-discovery-service"
  bank-discovery-service:
    build: ./discovery-service # Chemin vers le dossier contenant le Dockerfile pour construire l'image du service de découverte
    container_name: discovery-microservice # Nom du conteneur qui sera créé à partir de cette image
    ports:
      - '8761:8761' # Mapping des ports, rend le port 8761 du conteneur accessible sur le port 8761 de l'hôte
    expose:
      - '8761' # Expose le port 8761 à l'intérieur du réseau Docker, pour la communication interne entre les services
    healthcheck:
      # pour verifier si le microservice est bien demmarer
      test: ["CMD","curl","http://localhost:8761/actuator/health"]
      interval: 20s
      retries: 3

  # Définition du service "bank-config-service"
  bank-config-service:
    build: ./config-service
    container_name: config-microservice
    ports:
      - '9999:9999'
    expose:
      - '9999'
    environment:
      - DISCOVERY_SERVICE_URL=http://bank-discovery-service:8761/eureka
    depends_on:
      bank-discovery-service:
        # verifie si discovery est bien up a base du healthy check
        condition: service_healthy
    healthcheck:
      test: ["CMD","curl","http:/localhost:9999/actuator/health"]
      interval: 20s
      retries: 3


  # Définition du service "bank-customer-service"
  bank-customer-service:
    build: ./customer-service
    container_name: customer-service
    ports:
      - '8081:8081'
    expose:
      - '8081'
    environment:
      - DISCOVERY_SERVICE_URL=http://bank-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://bank-config-service:9999
    depends_on:
      bank-config-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD","curl","http:/localhost:8081/actuator/health"]
      interval: 40s
      retries: 3


  # Définition du service "bank-account-service"
  bank-account-service:
    build: ./account-service
    container_name: account-service
    ports:
      - '8082:8082'
    expose:
      - '8082'
    environment:
      - DISCOVERY_SERVICE_URL=http://bank-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://bank-config-service:9999
    depends_on:
      bank-customer-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD","curl","http:/localhost:8082/actuator/health"]
      interval: 40s
      retries: 3


  # Définition du service "bank-gateway-service"

  bank-gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - '8888:8888'
    expose:
      - '8888'
    environment:
      - DISCOVERY_SERVICE_URL=http://bank-discovery-service:8761/eureka
    depends_on:
      bank-config-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD","curl","http:/localhost:8888/actuator/health"]
      interval: 20s
      retries: 3

  # Définition du service "bank-gateway-service"  to check, I Think there is a problem

    #front-send-angular:
    #  build: ./angular-front-end
    #  container_name: front-send-angular
        # ports:
    #   - '82:80'
        #  expose:
    #   - '82'