# Routage static

spring:
  cloud:
    gateway:
      routes:
        - id: customer-service # Identifiant unique pour la route
          uri: http://localhost:8081 # URI du service de destination
          predicates: #conditions qui déterminent si une requête entrante correspond à cette route
            - Path=/service1/** # Correspondance des requêtes avec ce chemin
          filters:
            - AddRequestHeader=X-Request-Service1, Awesome # Ajoute un en-tête à la requête

        - id: account-service
          uri: http://localhost:8082
          predicates:
            - Path=/service2/**
          filters: #filtres pour modifier les requêtes et les réponses
            - AddRequestHeader=X-Request-Service2, MoreAwesome

      # Configuration globale des timeouts
      httpclient:
        connect-timeout: 1000 # Timeout de connexion en millisecondes
        response-timeout: 5000ms # Timeout de réponse

      # Activer le discovery client (e.g., Eureka), si utilisé
      discovery:
        locator:
          enabled: false

server:
  port: 8080 # Port sur lequel le Gateway écoute